[env:esp32s3-USB]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
board_build.partitions = partitions/esp32s3_8mb_ota_littlefs.csv
board_build.filesystem = littlefs
build_type    = release
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_ldf_mode    = deep+
lib_compat_mode = strict
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.15.5
    adafruit/Adafruit MCP9600 Library @ 2.0.4
    me-no-dev/ESPAsyncWebServer @ 3.6.0
    me-no-dev/AsyncTCP @ 3.3.2 
    adafruit/Adafruit BMP280 Library @ ^3.0.0
    adafruit/Adafruit AHTX0 @ ^2.0.0
    bblanchon/ArduinoJson @ ^7.0.0
lib_ignore =
upload_protocol = esptool
upload_port = COM4
monitor_speed = 115200
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0

[env:esp32s3-ota]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
board_build.partitions = partitions/esp32s3_8mb_ota_littlefs.csv
board_build.filesystem = littlefs
build_type    = release
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_ldf_mode    = deep+
lib_compat_mode = strict
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.15.5
    adafruit/Adafruit MCP9600 Library @ 2.0.4
    me-no-dev/ESPAsyncWebServer @ 3.6.0
    me-no-dev/AsyncTCP @ 3.3.2 
    adafruit/Adafruit BMP280 Library @ ^3.0.0
    adafruit/Adafruit AHTX0 @ ^2.0.0
    bblanchon/ArduinoJson @ ^7.0.0
lib_ignore =
upload_protocol = espota
upload_port = dyno-controller.local
upload_flags =
    --auth=metasense
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0